config/routes.rb
Rails.application.routes.draw do
  root to: 'kanbans#index'
  resources :kanbans do
    member do
      patch :move
    end
  end
  resources :kanban_bigs do
    member do
      patch :move
      delete :destroy
    end
  end
  resources :kanban_smalls do
    member do
      patch :move
      delete :destroy
    end
  end
  resources :cards do
    member do
      patch :move
      delete :destroy
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :kanban_small
end

app/models/kanban.rb
class Kanban < ApplicationRecord
  has_many :kanban_bigs
end

app/models/kanban_big.rb
class KanbanBig < ApplicationRecord
  has_many :kanban_smalls
  belongs_to :kanban
end

app/models/kanban_small.rb
class KanbanSmall < ApplicationRecord
  has_many :cards
  belongs_to :kanban_big
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kanbans_controller.rb
class KanbansController < ApplicationController
  before_action :set_kanban, only: %i[ show edit update destroy ]

  # GET /kanbans or /kanbans.json
  def index
    @kanbans = Kanban.all
  end

  # GET /kanbans/1 or /kanbans/1.json
  def show
  end

  # GET /kanbans/new
  def new
    @kanban = Kanban.new
  end

  # GET /kanbans/1/edit
  def edit
  end

  # POST /kanbans or /kanbans.json
  def create
    @kanban = Kanban.new(kanban_params)

    respond_to do |format|
      if @kanban.save
        format.html { redirect_to kanban_url(@kanban), notice: "Kanban was successfully created." }
        format.json { render :show, status: :created, location: @kanban }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kanban.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kanbans/1 or /kanbans/1.json
  def update
    respond_to do |format|
      if @kanban.update(kanban_params)
        format.html { redirect_to kanban_url(@kanban), notice: "Kanban was successfully updated." }
        format.json { render :show, status: :ok, location: @kanban }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kanban.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kanbans/1 or /kanbans/1.json
  def destroy
    @kanban.destroy

    respond_to do |format|
      format.html { redirect_to kanbans_url, notice: "Kanban was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kanban
      @kanban = Kanban.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kanban_params
      params.require(:kanban).permit(:name, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/kanbans/_form.html.erb
<%= simple_form_for(@kanban) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/kanbans/edit.html.erb
<h1>Editing Kanban</h1>

<%= render 'form', kanban: @kanban %>

<%= link_to 'Show', @kanban %> |
<%= link_to 'Back', kanbans_path %>

app/views/kanbans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kanbans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kanbans.each do |kanban| %>
      <tr>
        <td><%= kanban.name %></td>
        <td><%= kanban.description %></td>
        <td><%= link_to 'Show', kanban %></td>
        <td><%= link_to 'Edit', edit_kanban_path(kanban) %></td>
        <td><%= link_to 'Destroy', kanban, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kanban', new_kanban_path %>

app/views/kanbans/new.html.erb
<h1>New Kanban</h1>

<p>テスト</p>
<script type="text/javascript">
  $(document).ready(function() {
    $("p").text("成功！！");
  });
</script>

<%= render 'form', kanban: @kanban %>

<%= link_to 'Back', kanbans_path %>

app/views/kanbans/show.html.erb
<nav class="navbar navbar-expand-sm navbar-info bg-info mt-3 mb-3">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">モード1</li>
      <li class="nav-item active">モード2</li>
      <li class="nav-item active">モード3</li>
    </ul>
  </div>
</nav>
      
<p id="notice"><%= notice %></p>

<div class="kanban" data-id="<%= @kanban.id %>">
  <% @kanban.kanban_bigs.each do |big| %>
    <div id="kanban-big" class="kanban-big" data-big-id=<%= big.id %> >
      <div class="kanban-big-name"><%= big.name %></div>
      <% big.kanban_smalls.each do |small| %>
        <ul class="kanban-small" data-small-id=<%= small.id %> >
        <li class="kanban-small-name"><%= small.name %></li>
        <% small.cards.sort_by{ |card| card.position}.each do |item| %>
          <li class="kanban-col-item" data-item-id=<%= item.id %> >
          <%= item.content %>
          </li>
        <% end %>
        </ul>
      <% end %>
    </div>
  <% end %>
</div>

<%= link_to 'Edit', edit_kanban_path(@kanban) %> |
<%= link_to 'Back', kanbans_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DragndropKanbanBigSmallApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- JavaScript Bundle with Popper -->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <%= stylesheet_pack_tag 'hello_vue' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_pack_tag 'hello_vue' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>